CLASS LHC_ZCAS_GEN2P DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUIDKEY FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  ZCAS_GEN2P~CalculateUuidKey .
ENDCLASS.

CLASS LHC_ZCAS_GEN2P IMPLEMENTATION.
  METHOD CALCULATEUUIDKEY.
  ENDMETHOD.
ENDCLASS.
